name: Issue to Pull Request

on:
  issues:
    types: [opened, edited]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd scripts && npm i --only=production
      - run: cd scripts/actions && npx esno ./loader.ts ${{github.token}} issue-pr
